### ISSUE TITLE
popcorn api unavailable

### ISSUE THREAD

**Issue by pljp000** [sharkone/BitTorrent.bundle#114]
I tried getting to https://api-fetch.website/tv with my browser get see the following: Cannot GET /. I've restarted my pc and plex and still cannot access.

**Comment by codcheeks** [comment]
yup me too it seems that it is down too bad one of the favs of plugins

**Comment by crisfduran** [comment]
@soodkhah How do you make your call with curl? I get the same "Cannot GET /" response when using curl.

**Comment by pljp000** [comment]
I'm kind of wondering if Sharkone is on vacation, or no longer interested in this software.

**Comment by soodkhah** [comment]
> @soodkhah How do you make your call with curl? I get the same "Cannot GET /" response when using curl.
curl https://tv-v2.api-fetch.website/status

If you take the /status out, it will be "Cannot GET /". The troubleshoot test sends the request to /status.

**Comment by michaelllucas** [comment]
Did anyone manage to fix this issue ? Suddenly the plugin is not working any more as Popcorn API is unavailable

**Comment by pljp000** [comment]
No, I was hoping Sharkone would respond.

**Comment by shoguevara** [comment]
Seems like we can only thank Sharkone for the job he've done and try to fix this on our own. I've noticed that a lot of people forked this repo, bu none of then made any significant change. Anyway we might try to ask them for help - unfortunately I personally don't have any skills to do it by myself

**Comment by Conman2344** [comment]
Fix: https://github.com/Conman2344/BitTorrent.bundle

**Comment by pljp000** [comment]
Thank you Conman, Things are listing but plugin's are not responding.

**Comment by Conman2344** [comment]
Ill take a look tomorrow, where did you get to before it stops responding?

**Comment by sharkone** [comment]
I'll try and integrate the fix tonight or tomorrow.

**Comment by pljp000** [comment]
Hi Thomas & Conor,

How is it going? Does it look like you'll be able to fix the bundle?

**Comment by sharkone** [comment]
There's still some issues in my testing. I'll have a look.

**Comment by soodkhah** [comment]
@sharkone 
Popcorn server has Cloudflare in front. I looked it up and figured it is a Proxy/Firewall. Tried to figure out why it blocks sent by the Plex while it does not block my simple curl. It is because of the user agent. I copied the same user agent Plex Http client sends and got the same response (403) from popcorn. I will paste the details under this comment. I guess bottom line is that the Cloudflare has kind of blocking mechanism based on the request load. I believe it has blocked Plex requests possibly mistaking it with a DDOS attack. 
here is the sample blocked request: Please read the next request which sends an arbitrary User Agent as well(200 ok)
curl -vvv  https://api-fetch.website/tv/status -sL -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.74.9 (KHTML, like Gecko)'
*   Trying 104.24.28.84...
* TCP_NODELAY set
* Connected to api-fetch.website (104.24.28.84) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=ssl373605.cloudflaressl.com
*  start date: Jan 11 00:00:00 2019 GMT
*  expire date: Jul 20 23:59:59 2019 GMT
*  subjectAltName: host "api-fetch.website" matched cert's "api-fetch.website"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x564205fb8900)
> GET /tv/status HTTP/2
> Host: api-fetch.website
> Accept: */*
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.74.9 (KHTML, like Gecko)
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 403 
< date: Mon, 21 Jan 2019 02:23:16 GMT
< content-type: text/html; charset=UTF-8
< set-cookie: __cfduid=d5ecfa5edb78fc82daee42edaf684110b1548037396; expires=Tue, 21-Jan-20 02:23:16 GMT; path=/; domain=.api-fetch.website; HttpOnly
< cache-control: max-age=15
< expires: Mon, 21 Jan 2019 02:23:31 GMT
< x-frame-options: SAMEORIGIN
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
< cf-ray: 49c6515fca073042-YYZ
< 
<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<title>Access denied | api-fetch.website used Cloudflare to restrict access</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>


<script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script>
<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>



</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1>
          <span class="cf-error-type" data-translate="error">Error</span>
          <span class="cf-error-code">1020</span>
          <small class="heading-ray-id">Ray ID: 49c6515fca073042 &bull; 2019-01-21 02:23:16 UTC</small>
        </h1>
        <h2 class="cf-subheadline">Access denied</h2>
      </div>

      <section></section>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="what_happened">What happened?</h2>
            <p>This website is using a security service to protect itself from online attacks.</p>
          </div>

          
        </div>
      </div>

      <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">Cloudflare Ray ID: <strong>49c6515fca073042</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Your IP</span>: 204.225.214.39</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div>


    </div>
  </div>

  <script type="text/javascript">
  window._cf_translation = {};
  
  
</script>

</body>
</html>
----------------------------------------------------------------------------------------------------

Now the healthy one:
 curl -vvv  https://api-fetch.website/tv/status -sL -H 'User-Agent: howisitgoing'                                                         
*   Trying 104.24.28.84...
* TCP_NODELAY set
* Connected to api-fetch.website (104.24.28.84) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=ssl373605.cloudflaressl.com
*  start date: Jan 11 00:00:00 2019 GMT
*  expire date: Jul 20 23:59:59 2019 GMT
*  subjectAltName: host "api-fetch.website" matched cert's "api-fetch.website"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55a5927da900)
> GET /tv/status HTTP/2
> Host: api-fetch.website
> Accept: */*
> User-Agent: howisitgoing
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< date: Mon, 21 Jan 2019 02:34:02 GMT
< content-type: application/json; charset=utf-8
< content-length: 235
< set-cookie: __cfduid=ddee58685e4e19587985e1bf4b89839de1548038042; expires=Tue, 21-Jan-20 02:34:02 GMT; path=/; domain=.api-fetch.website; HttpOnly
< x-powered-by: Express
< etag: W/"eb-2WAn/3u8fMcjrU4xXPwA6A"
< x-response-time: 15.609ms
< vary: Accept-Encoding
< x-varnish: 303235359 302943964
< via: 1.1 varnish-v4
< x-varnish: 196546371 172966555
< via: 1.1 varnish-v4
< accept-ranges: bytes
< expires: Mon, 28 Jan 2019 02:34:02 GMT
< cache-control: max-age=604800
< strict-transport-security: max-age=63072000; preload
< access-control-allow-origin: *
< strict-transport-security: max-age=15638400
< x-frame-options: DENY
< x-content-type-options: nosniff
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
< cf-ray: 49c6612338973030-YYZ
< 
* Connection #0 to host api-fetch.website left intact
{"repo":"https://github.com/popcorn-official/popcorn-api.git","server":"serv01","status":"Scraping YTS","totalAnimes":704,"totalMovies":10394,"totalShows":3071,"updated":1548036000,"uptime":1688810,"version":"2.2.3","commit":"6c8a9a4"}

**Comment by sharkone** [comment]
Published release 1.1.2, available through the internal plugin update system. Seems to be working properly again. Thanks @Conman2344 for your help.

**Comment by ViktorCapulet** [comment]
Download Strem.io I’ve been using it for about 10 years now. 
You can take Netflix and every platform remotely like it even the television and it’s still killing it. TV shows are on STREMIO the day after they air.
